### ISSUE TITLE
Russian language issues.

### ISSUE THREAD

**Issue by skywinder** [FormatterKit/FormatterKit#169]
Hi. Just want to point out that it not works correct for Russian.
I will try to improve it later, just want declare in issue to not forget about details.

1.
- "1 hour from now" 
- in Russian looks like "1 час через" 
- should be "через 1 час"

2.
- "4 minutes ago" 
- looks like "4 минут назад"
- should be "4 минут**ы** назад"
- "минуты" applicable for 2-4 values only. (5+ should remain with the same plural rules)

That it's now easy to fix - it's need to apply some big refactoring in code. I will try to implement it carefully later.

**Comment by yas375** [comment]
Did you see https://github.com/mattt/TTTLocalizedPluralString? I'm thinking about adding it as a dependency to FormatterKit to solve this problem. Different languages have different plural rules and it's nice that there is a small library intended to solve that problem and to provide a unified api for this.

It will also solve the 2nd issue described in #212.

@skywinder @tevelee thoughts?

**Comment by tevelee** [comment]
@yas375 I didn't know about the lib, but I just took a look and it's great. I believe it would solve the 2nd issue in #212 if we include it as a dependency.

**Comment by mattt** [comment]
As discussed in #230, adding support for grammatical gender is beyond the scope of this project, which is in the process of being discontinued.
