### ISSUE TITLE
TTTLocationFormatterCoordinateStyle.TTTDegreesFormat

### ISSUE THREAD

**Issue by msjulie** [FormatterKit/FormatterKit#173]
It seems wrong that a location formatted with  TTTDegreesFormat  (ie 45.5200° N, 122.6819° W)
format should ever have a - value for the degree.   Entering a location so formatted, with a negative (ie -45...) into google maps yields an error or incorrect location.  Functionally a change something like

```
        if (degrees < 0) {
            degrees *= -1;
        }
```

seems called for....

**Comment by mattt** [comment]
Under what circumstances is this behavior occurring?

**Comment by msjulie** [comment]
Given 2 formatted output strings, pasted as-is into maps.google.com    

37° 19′ 22″ N, -122° 1′ 43″ W   !=   37° 19′ 22″ N, 122° 1′ 43″ W    

the second one is desired and a result of the quickie hack above;  feels like the - in front of 122 shouldn't be there.

**Comment by mattt** [comment]
Sorry, that's not what I meant.

Under what circumstances are you getting a negative degree output when using FormatterKit?

**Comment by msjulie** [comment]
Oops.. code snippet 

            let location = CLLocation(latitude: lat!, longitude: lng!)
            let formatter = TTTLocationFormatter()

            formatter.coordinateStyle = TTTLocationFormatterCoordinateStyle.DegreesMinutesSecondsFormat
            return formatter.stringFromLocation(location)

Location double values for the location are
    37.32058225935274,  -122.0291685903742

resulting in 37° 19′ 22″ N, -122° 1′ 43″ W

**Comment by monkeymike** [comment]
I can also reproduce this bug also. The `TTTGetDegreesMinutesSecondsFromCoordinateDegrees` method should do an absolute value on degrees after its finished calculating minutes and seconds.

**Comment by monkeymike** [comment]
Added PR #206 to address this.
