### ISSUE TITLE
Relative date string localization

### ISSUE THREAD

**Issue by sebastianludwig** [FormatterKit/FormatterKit#184]
Hey, thanks for this lib! Is there a reason why the relative date strings in `TTTTimeIntervalFormatter` are localized in code instead of in the `.strings` files?

**Comment by sebastianludwig** [comment]
In the above mentioned commit I moved the strings into the `.strings` files where they belong. This also enables all the other translations that already contained the keys which were never used.

The translations in code covered a few special cases where languages have a special term for e.g. "day before yesterday" like _eergisteren_ in dutch. I didn't cover those and probably won't for a while. Once PR #189 is merged, feel free everybody to pick up from here.

The solution in my head uses `NSLocalizedStringWithDefaultValue` with a `notFound` default value to check if the key exists for the current locale and to returns `nil` from `idiomaticDeicticExpressionForStartingDate` if it does not.

**Comment by yas375** [comment]
👍 this is definitely going to be merged once we have locale-specific unit tests which I'm working on.

**Comment by sebastianludwig** [comment]
Very glad to see this pod isn't dead after all. Hate to see popular pods rot away because the one and only maintainer didn't add contributors in time. :+1:

**Comment by yas375** [comment]
Locale specific tests are in place! :)
@sebastianludwig are you still willing to update your 57aaf60 and to submit a pull request? ;)
