### ISSUE TITLE
Hungarian language issues

### ISSUE THREAD

**Issue by tevelee** [FormatterKit/FormatterKit#212]
# Issue No.1

The Hungarian language is tricky in some ways, because it handles affixes differently than most languages: the affix and the base word melts together in one transformed form. 
When using the past deictic expression format in time interval formatting for example, using a separate keyword for past sounds unnatural, instead we should use a different - transformed - word for the calendar units. 
### Examples
- Now "1 year ago" is directly translated to "1 év óta" (_"year" = "év", "ago" = "óta"_), but more naturally it would sound like "1 éve", where the word for "year" is transformed.
- "1 month ago" = "1 hónap óta" should be "1 hónapja"
- "1 week ago" = "1 hét óta" should be "1 hete"
- "1 day ago" = "1 nap óta" should be "1 napja"
- "1 hour ago" = "1 óra óta" should be "1 órája"
- "1 minute ago" = "1 perc óta" should be "1 perce"
- "1 second ago" = "1 másodperc óta" should be "1 másodperce"
## Proposal

Another open-source library on GitHub ([https://github.com/tomkowz/Swifternalization](https://github.com/tomkowz/Swifternalization)) has some awesome solutions, namely that you specify one localisation key for the translated word, but you can provide alternative forms which are basically the same word, but they're transformed in some way. Eg. plural form, past form, future form, etc. This way we can avoid lots of keys which are unused in most languages but important for others.
# Issue No.2

Another interesting language characteristic - which differs from English - is that when using multiple units specified with a number, the language does use a singular form of the units.
So English goes "1 week", "2 weeks" (with an extra "s"), but Hungarian "1 hét", "2 hét". Please not that the unit of the word did not change in singular and plural cases.
## Proposal

Like in issue _No.1_, there should be a unit specific formatting described in the translation. If you don't specify it the word remains the same, but for example singular, plural or empty forms can use different words in the translations. Please look at this solution I mentioned above: [https://github.com/tomkowz/Swifternalization#inequality-expressions](https://github.com/tomkowz/Swifternalization#inequality-expressions)
# Issue No.3

Hungarian language does NOT use the Oxford comma in any cases so in lists like "1 week, 2 days, and 3 hours" there should not be a comma in the last place. The rule here is you either use a linker like "and / or" or you use a comma, but not both. So in Hungarian "1 hét, 2 nap és 3 óra" is the correct form.
## Proposal

The list formatter should also have an `NSLocale` property which sets a default value how the specific locale uses lists.

**Comment by yas375** [comment]
@tevelee am I right the the 1st issue described here was implemented in #211 or is there something left?

**Comment by tevelee** [comment]
@yas375 the current implementation in #211 is just partial. As I highlighted in the issue it's okay, but doesn't sound natural. I tried to solved these to sound perfect in Hungarian in my previous pull request (#192), the implementation would look something like this: https://github.com/mattt/FormatterKit/pull/192/commits/abb618b43c43d857af8ef5039f54015823479c05#diff-02b541266cad825d559e59126e606ecaR521
