### ISSUE TITLE
French language issues with ordinal number

### ISSUE THREAD

**Issue by gloryluu** [FormatterKit/FormatterKit#230]
It should be "2ème, 3ème". Not 2e, 3e

**Comment by yas375** [comment]
Could you please provide me with an example of code I can use in a unit test?

**Comment by mattt** [comment]
[French ordinal abbreviations](https://en.wiktionary.org/wiki/Appendix:French_numbers#Digit_abbreviations) require gender to be conjugated correctly. In my experience, very few software localizations take this into account and default to the masculine form (e) as used here. Adding support for grammatical gender would be a lot of work, and beyond the current scope of the project.

**Comment by mattt** [comment]
As described [in the README](https://github.com/FormatterKit/FormatterKit#example-usage-5), the correct ordinal suffix depends on the grammatical gender of the subject. To get "ème" instead of "e", specify `TTTOrdinalNumberFormatterFemaleGender`
