### ISSUE TITLE
[Feature] TTTArrayFormatter "or" instead of "and"

### ISSUE THREAD

**Issue by danhd123** [FormatterKit/FormatterKit#243]
TTTArrayFormatter's sentence style currently only supports a localized version of `@[@"Jeff", @"Mary", @"Allen"]` -> `"Jeff, Mary, and Allen"`. I'd like to be able to flip a switch, something like a `@property (nonatomic, assign) BOOL describesAny` to do `@[@"Jeff", @"Mary", @"Allen"]` -> `@"Jeff, Mary, or Allen"` (and optionally, a second switch `describesAll`, on by default, which produces `and`; both on would produce `and/or`). While I can work around this missing feature in English, I don't know if list construction in other languages changes when describing any element of a list rather than all of them.

**Comment by mattt** [comment]
Thanks for sharing your feature request, @danhd123. I think this is an interesting idea, but as you mentioned, I'm not at all confident about the universality of interchanging conjunctives and disjunctives like this. Without a strong motivating use case, I'm compelled to leave things scoped as they are.
